#!/usr/bin/env python3
"""Rebuilds the status page, README.md of the status branch, from the records collect.py makes.

    render.py DIR [--record run.json --manifest compatibility.yml]

With --record, the run and the manifest of the repository it came from are stored first, under
DIR/data/<repo>/ (<workflow>.json, compatibility.yml). The page is then rebuilt from everything
under DIR/data and nothing else, so two runs publishing at the same time only have to retry on
top of each other.
"""
import argparse
import json
import pathlib
import re
import shutil

import yaml

ORG = 'Vania-Metrics'
PLATFORMS = [
    ('paper', 'Paper'), ('purpur', 'Purpur'), ('folia', 'Folia'), ('spigot', 'Spigot'),
    ('bukkit', 'CraftBukkit'), ('sponge', 'Sponge'), ('velocity', 'Velocity'),
    ('bungeecord', 'BungeeCord'), ('waterfall', 'Waterfall'), ('geyser', 'Geyser'),
]
OK, KO, NOT_RUN, UNTESTED, NOT_PORTED, NO_PLUGIN, UNKNOWN = '✅', '❌', '⚪', '🧪', '🚫', '➖', '❔'
RESULT = {'success': OK, 'failure': KO, 'cancelled': NOT_RUN}


def esc(value):
    return str(value).replace('|', '\\|')


def bare(version):
    """'7.0.17 (7.0.18+ drops 1.21.11)' is 7.0.17."""
    return re.sub(r'\s*\(.*\)\s*$', '', version)


def when(iso, short=False):
    if not iso:
        return '—'
    return iso[5:10] if short else f'{iso[:10]} {iso[11:16]} UTC'


def repo_url(repo):
    return f'https://github.com/{ORG}/{repo}'


def load(root):
    repos = {}
    data = root / 'data'
    for d in sorted(data.iterdir()) if data.is_dir() else []:
        if not d.is_dir():
            continue
        manifest = d / 'compatibility.yml'
        repos[d.name] = {
            # Every scalar a string: "yes", "no" and "on" must not turn into booleans.
            'manifest': (yaml.load(manifest.read_text(encoding='utf-8'), Loader=yaml.BaseLoader) or {})
            if manifest.exists() else {},
            'runs': {j.stem: json.loads(j.read_text(encoding='utf-8')) for j in sorted(d.glob('*.json'))},
        }
    return repos


def outcomes(run, platform):
    """The cells of that platform in the run: velocity-3.5.1 and velocity-4.2.1 are velocity's."""
    return {c: o for c, o in (run or {}).get('cells', {}).items() if c.split('-')[0] == platform}


def verdict(outs):
    if any(o == 'failed' for o in outs.values()):
        return KO
    if outs and all(o == 'passed' for o in outs.values()):
        return OK
    return ''


def symbol(claim, plugin, outs):
    if claim in ('yes', 'tested'):
        return verdict(outs) or NOT_RUN
    if claim == 'untested':
        return UNTESTED + verdict(outs)
    if claim == 'no':
        return {'yes': NOT_PORTED, 'bundled': NOT_PORTED, 'no': NO_PLUGIN}.get(plugin, UNKNOWN)
    return UNKNOWN


def cells_text(outs):
    if not outs:
        return '—'
    parts = []
    for cell, outcome in outs.items():
        mark = {'passed': OK, 'failed': KO}.get(outcome, NOT_RUN)
        variant = cell.partition('-')[2]
        parts.append(f'{mark} {variant}' if variant else mark)
    return ' · '.join(parts)


def run_line(run):
    if not run:
        return 'no run recorded yet'
    return (f'[{RESULT.get(run["result"], UNKNOWN)} {run["result"]}]({run["url"]}) · {when(run["finished"])}'
            f' · commit `{run["sha"][:7]}` · {run["event"]}')


def render(repos):
    core = repos.get('core', {'manifest': {}, 'runs': {}})
    cm = core['manifest']
    core_ref = f'v{cm["version"]}' if cm.get('version') else None
    collectors = {k: v for k, v in repos.items() if k.startswith('collector-')}
    finished = [r['finished'] for e in repos.values() for r in e['runs'].values() if r.get('finished')]
    green = sum(1 for e in collectors.values() if e['runs'].get('ci', {}).get('result') == 'success')

    out = []
    w = out.append
    w('<!-- Generated by .github/status/render.py (Vania-Metrics/.github) after every CI run on main. '
      'Do not edit by hand. -->')
    w('# VaniaMetrics — compatibility and CI status')
    w('')
    w('Where the core and every collector run, at which versions, and what their latest CI run on '
      '`main` found. Each repository publishes here at the end of its CI: the matrix is its '
      '`compatibility.yml`, the results are its tests on real servers (a server started in a '
      'container, the plugins loaded, `/metrics` read, then a clean shutdown with a clean log).')
    w('')
    w(f'**Minecraft {cm.get("minecraft", "?")}** · **core {cm.get("version", "?")}** · '
      f'collectors green: **{green}/{len(collectors)}** · last update: {when(max(finished, default=None))}')
    w('')
    w(f'{OK} runs there, passed in the latest CI run · {KO} runs there, failed in the latest CI run · '
      f'{NOT_RUN} runs there, not tested by the latest CI run · {UNTESTED} expected to run, not verified '
      f'yet · {NOT_PORTED} the target plugin runs there, the collector does not yet · {NO_PLUGIN} the '
      f'target plugin itself does not run there · {UNKNOWN} unknown')
    w('')

    # Collectors, one line each.
    w('## Collectors')
    w('')
    w('| Collector | Target plugin | Built against | Core | Java | Latest CI | '
      + ' | '.join(name for _, name in PLATFORMS) + ' |')
    w('|---|---|---|---|---|---|' + ':-:|' * len(PLATFORMS))
    for repo, e in collectors.items():
        m, run = e['manifest'], e['runs'].get('ci')
        plugin = m.get('plugin', {})
        # The manifest may explain a version in parentheses; the details section keeps that.
        built = bare(plugin.get('compiled-against', '?'))
        latest = bare(plugin.get('latest-for-minecraft', ''))
        if latest and latest != built:
            built += f' (latest {latest})'
        ref = m.get('core', '?')
        if core_ref and ref != core_ref:
            ref += ' ⚠️'
        java = (run or {}).get('runtime', '').removeprefix('java') or '—'
        ci = f'[{RESULT.get(run["result"], UNKNOWN)} {when(run["finished"], True)}]({run["url"]})' if run else '—'
        platforms = m.get('platforms', {})
        marks = [symbol(platforms.get(p, {}).get('collector'), platforms.get(p, {}).get('plugin'),
                        outcomes(run, p)) if p in platforms else UNKNOWN for p, _ in PLATFORMS]
        w(f'| [{repo.removeprefix("collector-")}]({repo_url(repo)}) | {esc(plugin.get("name", "?"))} | '
          f'{esc(built)} | {esc(ref)} | {java} | {ci} | ' + ' | '.join(marks) + ' |')
    w('')

    # The core: the servers every cell runs on.
    w('## Core')
    w('')
    w(f'[core]({repo_url("core")}) **{cm.get("version", "?")}**, Java 21. Every collector cell runs on the '
      'same servers as the core\'s, pinned below.')
    w('')
    w(f'- Every platform (monthly, and by hand before a release): {run_line(core["runs"].get("platforms"))}')
    w(f'- Every push (unit tests, then Paper): {run_line(core["runs"].get("build"))}')
    w('')
    w('| Platform | Jar | Status | Tested on | Every platform | Notes |')
    w('|---|---|---|---|---|---|')
    for p, name in PLATFORMS:
        c = cm.get('platforms', {}).get(p)
        if c is None:
            continue
        outs = outcomes(core['runs'].get('platforms'), p)
        w(f'| {name} | `{esc(c.get("jar", "?"))}` | {esc(c.get("status", "?"))} | {esc(c.get("on", ""))} | '
          f'{cells_text(outs)} | {esc(c.get("note", ""))} |')
    w('')

    # Every collector in full.
    w('## Collectors in detail')
    for repo, e in collectors.items():
        m, run = e['manifest'], e['runs'].get('ci')
        plugin = m.get('plugin', {})
        version = m.get('core', '?').removeprefix('v')
        w('')
        w(f'### {repo.removeprefix("collector-")}')
        w('')
        target = esc(plugin.get('name', '?'))
        if plugin.get('source'):
            target = f'[{target}]({plugin["source"]})'
        line = (f'[{repo}]({repo_url(repo)}) · targets {target} **{esc(plugin.get("compiled-against", "?"))}**'
                f' (latest for {m.get("minecraft", "?")}: {esc(plugin.get("latest-for-minecraft", "?"))})'
                f' · jar `vania-metrics-{repo}-{version}.jar` · core {esc(m.get("core", "?"))}')
        if run and run.get('runtime'):
            line += f' · tested on Java {run["runtime"].removeprefix("java")}'
        w(line)
        w('')
        w(f'Latest CI: {run_line(run)}')
        w('')
        w('| Platform | Target plugin | Collector | Latest CI |')
        w('|---|---|---|---|')
        for p, name in PLATFORMS:
            c = m.get('platforms', {}).get(p)
            if c is None:
                continue
            w(f'| {name} | {esc(c.get("plugin", "?"))} | {esc(c.get("collector", "?"))} | '
              f'{cells_text(outcomes(run, p))} |')
    w('')
    w('---')
    w('')
    w('How this page is made: the CI of every repository ends with a `status` job '
      '([`status.yml`](https://github.com/Vania-Metrics/.github/blob/main/.github/workflows/status.yml)), '
      'which reads the outcome of each cell from the run\'s logs (`collect.py`), stores it with the '
      'repository\'s `compatibility.yml` under `data/`, and rebuilds this page (`render.py`).')
    return '\n'.join(out) + '\n'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('dir', type=pathlib.Path)
    ap.add_argument('--record')
    ap.add_argument('--manifest')
    a = ap.parse_args()

    if a.record:
        rec = json.loads(pathlib.Path(a.record).read_text(encoding='utf-8'))
        d = a.dir / 'data' / rec['repo']
        d.mkdir(parents=True, exist_ok=True)
        target = d / f'{rec["workflow"]}.json'
        # A slow run finishing after a newer one must not put the page back in time.
        if target.exists() and json.loads(target.read_text(encoding='utf-8'))['finished'] > rec['finished']:
            print(f'{target}: a newer run is already recorded, keeping it')
        else:
            target.write_text(json.dumps(rec, indent=2) + '\n', encoding='utf-8')
            if a.manifest:
                shutil.copyfile(a.manifest, d / 'compatibility.yml')
    (a.dir / 'README.md').write_text(render(load(a.dir)), encoding='utf-8')


if __name__ == '__main__':
    main()
